"use client";

import { Info, Calendar } from "lucide-react";
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from "recharts";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

export interface RevenueChartResponse { year: number; summary: { totalRevenue: number }; chartData: { month: string; totalRevenue: number }[]; }
function CustomTooltip({ active, payload, label }: { active?: boolean; payload?: { payload: { totalRevenue: number } }[]; label?: string }) { if (!active || !payload?.length) return null; return <div className="rounded-2xl border border-border bg-popover px-5 py-3 text-center shadow-[0_8px_25px_rgba(0,0,0,0.12)]"><p className="text-[10px] font-medium leading-none text-muted-foreground">Revenue</p><p className="my-1 text-base font-bold leading-tight text-foreground">USD {payload[0].payload.totalRevenue}</p><p className="text-[10px] font-medium leading-none text-muted-foreground">{label}</p></div>; }

export default function RevenueChartCard({ data, isLoading }: { data?: RevenueChartResponse; isLoading?: boolean }) { const chartData = data?.chartData || []; return <div className="px-6"><Card className="rounded-2xl bg-card p-6 font-sans shadow-xs md:p-8"><CardHeader className="mb-8 flex flex-row items-center justify-between space-y-0 p-0"><div className="flex items-center gap-2"><CardTitle className="text-base font-bold text-[#2A7D6F] md:text-lg">Revenue</CardTitle><Info className="h-4 w-4 text-muted-foreground" /></div><Badge variant="outline" className="flex items-center gap-2 rounded-lg bg-background px-3 py-1.5 text-xs font-normal text-muted-foreground"><span>{data ? `${data.year} · USD ${data.summary.totalRevenue}` : "Loading..."}</span><Calendar className="h-3.5 w-3.5 text-muted-foreground" /></Badge></CardHeader><CardContent className="p-0"><div className="h-[340px] w-full">{isLoading ? <div className="grid h-full place-items-center text-sm text-slate-400">Loading revenue chart...</div> : <ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData} margin={{ top: 40, right: 10, left: -20, bottom: 0 }}><defs><linearGradient id="chartGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4A8AF4" stopOpacity={0.25} /><stop offset="100%" stopColor="#4A8AF4" stopOpacity={0.01} /></linearGradient></defs><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: "#94A3B8", fontSize: 11 }} dy={12} /><YAxis axisLine={false} tickLine={false} tick={{ fill: "#94A3B8", fontSize: 11 }} /><Tooltip content={<CustomTooltip />} cursor={{ stroke: "transparent" }} /><Area type="natural" dataKey="totalRevenue" stroke="#2A7D6F" strokeWidth={3} fillOpacity={1} fill="url(#chartGradient)" activeDot={{ r: 6, fill: "#2A7D6F", stroke: "#ffffff", strokeWidth: 2.5 }} /></AreaChart></ResponsiveContainer>}</div></CardContent></Card></div>; }
